### ISSUE TITLE
number_precision: 2.0.1+1 该版本和以前版本中小数计算出现计算结果错误

### ISSUE THREAD

**Issue by xxxxxiaojiu** [luoyelusheng/number_precision#1]
在Dart文件中使用  number_precision: 2.0.1+1 该版本和以前版本，在多小数点计算的情况下会出现计算结果值错误的问题，如下图所示：
![tg_image_625118688](https://user-images.githubusercontent.com/87772410/149465134-1dab2c9d-5c82-4751-a161-bb74b57fb4f4.jpeg)

**Comment by luoyelusheng** [comment]
OK，我这边修复一下
