### ISSUE TITLE
四舍五入方法异常

### ISSUE THREAD

**Issue by flyzebraV** [luoyelusheng/number_precision#3]
print(NP.round(0.665, 2)); // 0.67 对的
  print(NP.round(12.665, 2)); // 12.67 对的
  print(NP.round(2461.5384615384614, 6)); // 错的 0.742802

**Comment by flyzebraV** [comment]
print(NP.times(2461.5384615384614, 1000000)); // 错的 742802.1056072144

**Comment by luoyelusheng** [comment]
ok，我这边修复一下
